In [1]:
import pandas as pd
df = pd.read_csv('../data/train.csv')

In [2]:
df.drop(['team_name','confederation'],axis=1,inplace=True)

In [19]:
df[df.duplicated()].shape

(0, 25)

In [20]:
df[df.duplicated()]

Empty DataFrame
Columns: [team_name, country_code, confederation, fifa_rank, fifa_points, wins_last_10_matches, losses_last_10_matches, draws_last_10_matches, win_rate_last_year, goals_scored_avg, goals_conceded_avg, clean_sheets_last_10, shots_per_game, shots_on_target_ratio, avg_player_rating, star_players_count, market_value_million_eur, experience_avg_caps, coach_experience_years, recent_form_score, possession_avg, passing_accuracy, host_advantage, travel_distance_avg, climate_similarity_score]
Index: []

[0 rows x 25 columns]

ENG - country_code already represents the classifictation, so I judged these two columns as unecessary

PTBR - Como o código do país representa o mesmo que team_name, e tem menos letras, acho que utilizar apenas country_code já é o suficiente.

In [ ]:
df.head()

In [ ]:
df.isnull().sum()

ENG  - No null data, so no fit.

PTBR - Sem nulos, então sem preenchimento de dados nulos.

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df.head()

In [3]:
df = pd.get_dummies(df, columns=['country_code'])

In [4]:
df.head()

,fifa_rank,fifa_points,wins_last_10_matches,losses_last_10_matches,draws_last_10_matches,win_rate_last_year,goals_scored_avg,goals_conceded_avg,clean_sheets_last_10,shots_per_game,...,country_code_SEN,country_code_SRB,country_code_SUI,country_code_SWE,country_code_TUN,country_code_TUR,country_code_UKR,country_code_URU,country_code_USA,country_code_WAL
0,18,1675.2,5,4,1,0.520,1.11,0.91,3,11.3,...,False,False,False,False,False,False,False,False,False,False
1,8,1831.2,7,2,1,0.690,2.31,0.76,5,19.2,...,False,False,False,False,False,False,False,False,False,False
2,6,1769.3,6,2,2,0.585,1.85,0.62,3,15.9,...,False,False,False,False,False,False,False,False,False,False
3,17,1663.4,7,1,2,0.584,1.40,1.09,2,15.6,...,False,False,False,False,False,False,False,False,False,False
4,28,1476.6,3,5,2,0.390,0.95,1.97,2,6.2,...,False,False,False,False,False,False,False,False,False,False

In [5]:
df['winner'].value_counts()

winner
0    527
1    473
Name: count, dtype: int64

ENG - Seems even

PTBR - Parece balanceado.

In [6]:
X = df.drop(columns=['winner'])

In [7]:
y = df['winner']

In [8]:
df.head()

,fifa_rank,fifa_points,wins_last_10_matches,losses_last_10_matches,draws_last_10_matches,win_rate_last_year,goals_scored_avg,goals_conceded_avg,clean_sheets_last_10,shots_per_game,...,country_code_SEN,country_code_SRB,country_code_SUI,country_code_SWE,country_code_TUN,country_code_TUR,country_code_UKR,country_code_URU,country_code_USA,country_code_WAL
0,18,1675.2,5,4,1,0.520,1.11,0.91,3,11.3,...,False,False,False,False,False,False,False,False,False,False
1,8,1831.2,7,2,1,0.690,2.31,0.76,5,19.2,...,False,False,False,False,False,False,False,False,False,False
2,6,1769.3,6,2,2,0.585,1.85,0.62,3,15.9,...,False,False,False,False,False,False,False,False,False,False
3,17,1663.4,7,1,2,0.584,1.40,1.09,2,15.6,...,False,False,False,False,False,False,False,False,False,False
4,28,1476.6,3,5,2,0.390,0.95,1.97,2,6.2,...,False,False,False,False,False,False,False,False,False,False

In [9]:
print(X)

     fifa_rank  fifa_points  wins_last_10_matches  losses_last_10_matches  \
0           18       1675.2                     5                       4
1            8       1831.2                     7                       2
2            6       1769.3                     6                       2
3           17       1663.4                     7                       1
4           28       1476.6                     3                       5
..         ...          ...                   ...                     ...
995          2       1973.5                     8                       0
996          5       1675.4                     6                       3
997         30       1713.1                     5                       2
998         48       1433.8                     1                       6
999         40       1463.2                     3                       7

     draws_last_10_matches  win_rate_last_year  goals_scored_avg  \
0                        1               0.520              1.11
1                        1               0.690              2.31
2                        2               0.585              1.85
3                        2               0.584              1.40
4                        2               0.390              0.95
..                     ...                 ...               ...
995                      2               0.708              1.96
996                      1               0.592              1.67
997                      3               0.575              1.60
998                      3               0.365              1.00
999                      0               0.360              0.62

     goals_conceded_avg  clean_sheets_last_10  shots_per_game  ...  \
0                  0.91                     3            11.3  ...
1                  0.76                     5            19.2  ...
2                  0.62                     3            15.9  ...
3                  1.09                     2            15.6  ...
4                  1.97                     2             6.2  ...
..                  ...                   ...             ...  ...
995                0.49                     3            14.7  ...
996                1.18                     4            13.2  ...
997                1.41                     3            12.2  ...
998                1.62                     0            10.0  ...
999                1.47                     2             6.5  ...

     country_code_SEN  country_code_SRB  country_code_SUI  country_code_SWE  \
0               False             False             False             False
1               False             False             False             False
2               False             False             False             False
3               False             False             False             False
4               False             False             False             False
..                ...               ...               ...               ...
995             False             False             False             False
996             False             False             False             False
997             False             False             False             False
998             False             False             False             False
999             False             False             False             False

     country_code_TUN  country_code_TUR  country_code_UKR  country_code_URU  \
0               False             False             False             False
1               False             False             False             False
2               False             False             False             False
3               False             False             False             False
4               False             False             False             False
..                ...               ...               ...               ...
995             False             False             False             False
996             False             False             False              True
997             False             False             False             False
998             False             False             False             False
999             False             False             False             False

     country_code_USA  country_code_WAL
0               False             False
1               False             False
2               False             False
3               False             False
4               False             False
..                ...               ...
995             False             False
996             False             False
997              True             False
998             False             False
999             False              True

[1000 rows x 71 columns]

In [10]:
print(y)

0      1
1      1
2      1
3      0
4      0
      ..
995    0
996    1
997    0
998    0
999    0
Name: winner, Length: 1000, dtype: int64

ENG - y as our target

PTBR - Definindo alvo

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [12]:
X_scaled = scaler.fit_transform(X)

In [14]:
df2 = pd.read_csv('../data/test.csv')

In [15]:
df2.head()

,team_name,country_code,confederation,fifa_rank,fifa_points,wins_last_10_matches,losses_last_10_matches,draws_last_10_matches,win_rate_last_year,goals_scored_avg,...,star_players_count,market_value_million_eur,experience_avg_caps,coach_experience_years,recent_form_score,possession_avg,passing_accuracy,host_advantage,travel_distance_avg,climate_similarity_score
0,Argentina,ARG,CONMEBOL,6,1784.8,6,2,2,0.747,2.18,...,5,1109.0,63,22,8.9,67.9,86.1,0,7.4,0.79
1,Ecuador,ECU,CONMEBOL,23,1669.3,6,4,0,0.482,1.55,...,2,386.0,38,11,5.6,54.0,77.3,0,6.7,0.75
2,Morocco,MAR,CAF,21,1714.0,4,5,1,0.582,1.40,...,3,375.0,25,14,5.3,53.7,83.9,0,7.2,0.41
3,China,CHN,AFC,35,1531.5,2,6,2,0.216,0.83,...,0,367.0,23,1,5.0,48.6,75.2,0,10.4,0.59
4,Croatia,CRO,UEFA,12,1697.9,7,2,1,0.606,1.96,...,4,461.0,50,17,5.7,58.7,88.8,0,6.0,0.59

In [18]:
df2['team_name'].value_counts()

team_name
France          16
Argentina       12
England         12
Brazil          11
USA              9
Senegal          9
Croatia          8
Spain            8
Germany          8
Colombia         7
Italy            7
Wales            7
Serbia           7
Austria          6
Poland           6
Portugal         6
Sweden           6
Cameroon         6
Japan            6
Netherlands      6
Australia        5
Tunisia          5
Egypt            5
Jamaica          5
Belgium          5
Ecuador          4
Turkey           4
Ukraine          4
South Korea      4
Iran             4
Denmark          4
Ghana            4
Uruguay          4
Costa Rica       4
Morocco          3
Mexico           3
Qatar            3
China            2
Saudi Arabia     2
Nigeria          2
Switzerland      2
New Zealand      2
Paraguay         2
Canada           2
Peru             1
Algeria          1
Honduras         1
Name: count, dtype: int64

In [21]:
df2[df2.duplicated()].shape

(0, 25)

In [22]:
df2[df2.duplicated()]

Empty DataFrame
Columns: [team_name, country_code, confederation, fifa_rank, fifa_points, wins_last_10_matches, losses_last_10_matches, draws_last_10_matches, win_rate_last_year, goals_scored_avg, goals_conceded_avg, clean_sheets_last_10, shots_per_game, shots_on_target_ratio, avg_player_rating, star_players_count, market_value_million_eur, experience_avg_caps, coach_experience_years, recent_form_score, possession_avg, passing_accuracy, host_advantage, travel_distance_avg, climate_similarity_score]
Index: []

[0 rows x 25 columns]

In [24]:
df.head()

,team_name,country_code,confederation,fifa_rank,fifa_points,wins_last_10_matches,losses_last_10_matches,draws_last_10_matches,win_rate_last_year,goals_scored_avg,...,star_players_count,market_value_million_eur,experience_avg_caps,coach_experience_years,recent_form_score,possession_avg,passing_accuracy,host_advantage,travel_distance_avg,climate_similarity_score
0,Argentina,ARG,CONMEBOL,6,1784.8,6,2,2,0.747,2.18,...,5,1109.0,63,22,8.9,67.9,86.1,0,7.4,0.79
1,Ecuador,ECU,CONMEBOL,23,1669.3,6,4,0,0.482,1.55,...,2,386.0,38,11,5.6,54.0,77.3,0,6.7,0.75
2,Morocco,MAR,CAF,21,1714.0,4,5,1,0.582,1.40,...,3,375.0,25,14,5.3,53.7,83.9,0,7.2,0.41
3,China,CHN,AFC,35,1531.5,2,6,2,0.216,0.83,...,0,367.0,23,1,5.0,48.6,75.2,0,10.4,0.59
4,Croatia,CRO,UEFA,12,1697.9,7,2,1,0.606,1.96,...,4,461.0,50,17,5.7,58.7,88.8,0,6.0,0.59

In [26]:
df['country_code'].value_counts().sum()

np.int64(250)

In [27]:
df2['country_code'].value_counts().sum()

np.int64(250)

In [28]:
print(df['country_code'].nunique())

47

In [29]:
print(df2['country_code'].nunique())

47